#pragma once
//TODO pch
#include <iostream>
#include <optional>
#include <string>
#include <cctype>
#include <cstdint>
#include <fstream>
#include <sstream>
#include <vector>
#include <array>
#include <unordered_map>